modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Better-Hunger/issues"

[[mods]]
modId="betterhunger"
updateJSONURL="https://updates.blamejared.com/get?n=betterhunger&gv=1.16.1"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.betterhunger]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.betterhunger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.betterhunger]]
    modId="bookshelf"
    mandatory=true
    versionRange="[6.1,)"
    ordering="AFTER"
    side="BOTH"