modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Better-Hunger/issues"
license="LGPL v2.1"

[[mods]]
modId="betterhunger"
updateJSONURL="https://updates.blamejared.com/get?n=betterhunger&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.betterhunger]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="SERVER"

[[dependencies.betterhunger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.betterhunger]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"